apiVersion: v1
kind: Service
metadata:
  name: productpage-nodeport
  namespace: bookinfo
  labels:
    app: productpage
    service: productpage
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: productpage
---
# Namespace for Bookinfo application
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  labels:
    name: bookinfo
    # Linkerd injection enabled (when Linkerd is stable)
    # linkerd.io/inject: enabled 