prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 15d
    storageSpec: {}

grafana:
  adminPassword: prom-operator
  persistence:
    enabled: false
  service:
    type: NodePort
    nodePort: 30300

alertmanager:
  alertmanagerSpec:
    retention: 120h
    storage: {}

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true 